name = "SatelliteToolboxPropagators"
uuid = "c2b69894-ea78-4e2b-9ba6-cedbbc3d14d7"
license = "MIT"
desc = "Orbit propagators for the SatelliteToolbox.jl ecosystem."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.0.1"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxSgp4 = "ba14ac17-bfc9-4710-a76f-b32930ef2339"
SatelliteToolboxTle = "7ff27aeb-5fff-4337-a9ee-a9fe6b7ed35e"

[compat]
Crayons = "4"
Reexport = "1"
SatelliteToolboxBase = "0.2"
SatelliteToolboxSgp4 = "2"
SatelliteToolboxTle = "1"
julia = "1.6"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
